version: "3"

services:
  nginx: 
    image: "nginx:stable-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www
    depends_on:
      - php
      - pgsql
      - redis
      
  php:
    build:
      context: .
      dockerfile: "dockerfile/php.dockerfile"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src:/var/www
  
  pgsql:
    image: ronasit/postgres:12.5
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: "secret123"
        POSTGRES_USER: pguser
        POSTGRES_DB: pgdb
        POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgre:/var/lib/postgresql/data

  redis:
    image: redis:6.2.3
    ports:
        - 6379:6379

  composer:
    build:
      context: .
      dockerfile: "dockerfile/composer.dockerfile"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src:/var/www
    
  artisan:
    build:
      context: .
      dockerfile: "dockerfile/php.dockerfile"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src:/var/www
    entrypoint: ["php", "/var/www/artisan"]